### ISSUE TITLE
Error message : TemplateWriterWriteError 

### ISSUE THREAD

**Issue by sdelon** [shalomscott/eleventy-plugin-embed-svelte#2]
Hello Shalom, 

First of all, thank you for this plugin that I can't wait to try to use. But I have a problem when running the command eleventy. I have a fresh new install of 11ty and added your plugin just to make a test, but when I hit npm run start to start eleventy, I have this error message : 

`
> Having trouble writing template: _site/index.html

`TemplateWriterWriteError` was thrown
> Octal literal in strict mode (Note that you need plugins to import files that are not JavaScript)
`

Do you know where this could come from ? Should I add some other plugin to this fresh blank install to be able to run ? Sorry for these newbie questions, but I would love to start this svelte and 11ty cross stack.
Thanks a lot and have a great day

**Comment by shalomscott** [comment]
So sorry I hadn't seen this issue until yesterday! Definitely not a newbie question since this was a legit problem and not obvious to track down. It seems that [**rollup-plugin-svelte**](https://github.com/sveltejs/rollup-plugin-svelte) has recently updated the default value of the `emitCss` option to `true`, which this plugin was not prepared to handle. Should be fixed in the newest release.

**Comment by shalomscott** [comment]
Let me know if the issue persists for you. Closing for now.
